name: pyfibre-py36
channels:
  - conda-forge
dependencies:
  - python==3.6.13
  - click==7.1.1
  - envisage==4.9.2
  - stevedore==1.29.0
  - pytables==3.5.1
  - pygments>=2.2.0
  - pyqt
  - scikit-image==0.16.2
  - xlwt==1.2.0
  - xlrd==1.2.0
  - matplotlib>=3.2.1
  - networkx==2.2
  - decorator==4.1.2
  - pip==21.3.1
  - pip:
    - scikit-learn==0.23.0
    - pandas==1.1.5
